# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.13.102"
  config.vm.hostname = "woocommerce"

  config.ssh.forward_agent = true

  config.vm.synced_folder "../", "/opt/fyndiq-woocommerce-module"

  config.vm.provision :shell, path: "./provision.sh"
  config.vm.provision "shell", inline: "service apache2 restart", run: "always"
end
