# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "parallels" do |v, override|
    override.vm.box = "parallels/ubuntu-14.04"
    override.vm.box_url = "https://vagrantcloud.com/parallels/ubuntu-14.04"
  end

  config.vm.network "private_network", ip: "192.168.13.102"
  config.vm.hostname = "woocommerce"

  config.ssh.forward_agent = true
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  config.vm.synced_folder "../", "/opt/fyndiq-woocommerce-module"

  config.vm.provision :shell, path: "./provision.sh"
  config.vm.provision "shell", inline: "service apache2 restart", run: "always"
end
